avoid-breaking-exported-api = false

too-many-arguments-threshold = 10
type-complexity-threshold = 500

allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-dbg-in-tests = true

doc-valid-idents = [
    "..",
    "GitHub",
    "PyPI",
    "OAuth",
    "WebSocket",
    "PostgreSQL",
    "SQLite",
    "SemVer",
    "OpenAPI",
    "TypeScript",
]
