name: autofmt

on:
  push:
    branches-ignore: [main]

jobs:
  autofmt:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: cargo fmt
      - run: ruff format . || true
      - run: git diff > format.patch
      - uses: actions/upload-artifact@v4
        with:
          name: format-patch
          path: format.patch
          if-no-files-found: warn
