name: ci

on:
  push:

jobs:
  fmt:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: cargo fmt --check

  clippy:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: cargo clippy --locked --all-targets --all-features -- -D warnings

  test:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: cargo test --locked --all-features

  doc:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: cargo doc --locked --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  ruff:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff check --output-format github .

  format:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: ruff format --check --diff .

  pyright:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: basedpyright

  pytest:
    runs-on: pool
    steps:
      - uses: actions/checkout@v7
      - run: uv sync --frozen
      - run: echo "$PWD/.venv/bin" >>"$GITHUB_PATH"
      - run: pytest
